//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tasks()
        {
            this.Teams = new HashSet<Teams>();
        }
    
        public int idTask { get; set; }
        public int idUser { get; set; }
        public int idProject { get; set; }
        public string NameTask { get; set; }
        public string DescriptionTask { get; set; }
        public string Priority { get; set; }
        public string DateAdd { get; set; }
        public string Comment { get; set; }
        public string Deadline { get; set; }
        public int idStatus { get; set; }
    
        public virtual Projects Projects { get; set; }
        public virtual Status Status { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teams> Teams { get; set; }
    }
}
